/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication22.arraylist;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ViviPc
 */
public class Intefaz extends javax.swing.JFrame {

       Clases usuario = new Clases();
       int posi;
       
    public Intefaz() {
        
        initComponents();
        primero.setEnabled(false);
        atras.setEnabled(false);
        ultimo.setEnabled(false);
        siguiente.setEnabled(false);
        buscar.setEnabled(false);
        posicion.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        primero = new javax.swing.JButton();
        ultimo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        posicion = new javax.swing.JTextField();
        curso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nombre");

        jLabel2.setText("Cedula");

        jLabel3.setText("Curso");

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        atras.setText("Atras");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        primero.setText("Primero");
        primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeroActionPerformed(evt);
            }
        });

        ultimo.setText("Ultimo");
        ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoActionPerformed(evt);
            }
        });

        jLabel4.setText("# DE Reguistrados ");

        posicion.setEditable(false);

        curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "primero", "segundo", "tercero", "cuarto", "quinto", "sexto", "septimo", "octavo", "noveno", "decimo" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(cedula)
                            .addComponent(curso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(atras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addComponent(siguiente)
                        .addGap(135, 135, 135)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ultimo)
                    .addComponent(primero)
                    .addComponent(buscar)
                    .addComponent(agregar))
                .addGap(94, 94, 94))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(primero)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ultimo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atras)
                            .addComponent(siguiente))))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        if(posi == usuario.tamaño()){
        if(nombre.getText().equals("") && cedula.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese los valores en las cajas de texto");
        } else {   
        usuario.ingresar(nombre.getText(), cedula.getText(), curso.getSelectedIndex());
        nombre.setText(null);
        cedula.setText(null);
        curso.setSelectedIndex(0);
        posicion.setText(String.valueOf(usuario.tamaño()));
        posi = usuario.tamaño();
        
        primero.setEnabled(true);
        atras.setEnabled(true);
        ultimo.setEnabled(false);
        siguiente.setEnabled(false);
        buscar.setEnabled(true);
        
        nombre.setEditable(true);
        cedula.setEditable(true);
        curso.setEnabled(true);
        }
        } else{
            
        nombre.setText(null);
        cedula.setText(null);
        curso.setSelectedIndex(0);
        posicion.setText(String.valueOf(usuario.tamaño()));
        posi = usuario.tamaño();
        
        nombre.setEditable(false);
        cedula.setEditable(false);
        curso.setEnabled(false);
        }
        
    }//GEN-LAST:event_agregarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        String buscar  = JOptionPane.showInputDialog(rootPane, "Ingrese el numero de cedula a buscar");
        int buscado = usuario.buscar(buscar);
        
        if(buscado != -1 && buscado == 0){
        posi = buscado;
        nombre.setText(usuario.getNombre(posi));
        cedula.setText(usuario.getCedula(posi));
        curso.setSelectedIndex(usuario.getCurso(posi));
        posicion.setText(String.valueOf(posi));
        
        primero.setEnabled(false);
        atras.setEnabled(false);
        ultimo.setEnabled(true);
        siguiente.setEnabled(true);
        
        nombre.setEditable(false);
        cedula.setEditable(false);
        curso.setEnabled(false);
        }
        
        if(buscado != -1 && buscado == usuario.tamaño() - 1){
        posi = buscado;
        nombre.setText(usuario.getNombre(posi));
        cedula.setText(usuario.getCedula(posi));
        curso.setSelectedIndex(usuario.getCurso(posi));
        posicion.setText(String.valueOf(posi));
        
        primero.setEnabled(true);
        atras.setEnabled(true);
        ultimo.setEnabled(false);
        siguiente.setEnabled(false);
        
        nombre.setEditable(false);
        cedula.setEditable(false);
        curso.setEnabled(false);
        }
        if(buscado != -1 && buscado != 0 && buscado != usuario.tamaño() - 1){
        posi = buscado;
        nombre.setText(usuario.getNombre(posi));
        cedula.setText(usuario.getCedula(posi));
        curso.setSelectedIndex(usuario.getCurso(posi));
        posicion.setText(String.valueOf(posi));
        
        primero.setEnabled(true);
        atras.setEnabled(true);
        ultimo.setEnabled(true);
        siguiente.setEnabled(true);
        
        nombre.setEditable(false);
        cedula.setEditable(false);
        curso.setEnabled(false);
        }
        
    }//GEN-LAST:event_buscarActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
     if(posi != usuario.tamaño() - 1){
            posi++;
        nombre.setText(usuario.getNombre(posi));
        cedula.setText(usuario.getCedula(posi));
        curso.setSelectedIndex(usuario.getCurso(posi));
        posicion.setText(String.valueOf(posi));
        
        nombre.setEditable(false);
        cedula.setEditable(false);
        curso.setEnabled(false);
        
        primero.setEnabled(true);
        atras.setEnabled(true);
        ultimo.setEnabled(true);
        siguiente.setEnabled(true);
        
        } else {
        primero.setEnabled(true);
        atras.setEnabled(true);
        ultimo.setEnabled(false);
        siguiente.setEnabled(false);
        
        nombre.setEditable(false);
        cedula.setEditable(false);
        curso.setEnabled(false);
        
        }
    }//GEN-LAST:event_siguienteActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        if(posi != 0){
            posi--;
        nombre.setText(usuario.getNombre(posi));
        cedula.setText(usuario.getCedula(posi));
        curso.setSelectedIndex(usuario.getCurso(posi));
        posicion.setText(String.valueOf(posi));
        
        nombre.setEditable(false);
        cedula.setEditable(false);
        curso.setEnabled(false);
        
        primero.setEnabled(true);
        atras.setEnabled(true);
        ultimo.setEnabled(true);
        siguiente.setEnabled(true);
        
        } else {
        primero.setEnabled(false);
        atras.setEnabled(false);
        ultimo.setEnabled(true);
        siguiente.setEnabled(true);
        
        nombre.setEditable(false);
        cedula.setEditable(false);
        curso.setEnabled(false);
        
        }
        
    }//GEN-LAST:event_atrasActionPerformed

    private void primeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeroActionPerformed
        posi = 0;
        nombre.setText(usuario.getNombre(posi));
        cedula.setText(usuario.getCedula(posi));
        curso.setSelectedIndex(usuario.getCurso(posi));
        posicion.setText(String.valueOf(posi));
        
        primero.setEnabled(false);
        atras.setEnabled(false);
        ultimo.setEnabled(true);
        siguiente.setEnabled(true);
        
        nombre.setEditable(false);
        cedula.setEditable(false);
        curso.setEnabled(false);
    }//GEN-LAST:event_primeroActionPerformed

    private void ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoActionPerformed
        // TODO add your handling code here:
        posi = usuario.tamaño() - 1;
        nombre.setText(usuario.getNombre(posi));
        cedula.setText(usuario.getCedula(posi));
        curso.setSelectedIndex(usuario.getCurso(posi));
        posicion.setText(String.valueOf(posi));
        
        primero.setEnabled(true);
        atras.setEnabled(true);
        ultimo.setEnabled(false);
        siguiente.setEnabled(false);
        
        nombre.setEditable(false);
        cedula.setEditable(false);
        curso.setEnabled(false);
    }//GEN-LAST:event_ultimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intefaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intefaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intefaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intefaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intefaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton atras;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField cedula;
    private javax.swing.JComboBox<String> curso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField posicion;
    private javax.swing.JButton primero;
    private javax.swing.JButton siguiente;
    private javax.swing.JButton ultimo;
    // End of variables declaration//GEN-END:variables
}
